// Code generated by protoc-gen-go.
// source: mapreduce.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	mapreduce.proto

It has these top-level messages:
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

func init() {
}

// Client API for Mapreduce service

type MapreduceClient interface {
}

type mapreduceClient struct {
	cc *grpc.ClientConn
}

func NewMapreduceClient(cc *grpc.ClientConn) MapreduceClient {
	return &mapreduceClient{cc}
}

// Server API for Mapreduce service

type MapreduceServer interface {
}

func RegisterMapreduceServer(s *grpc.Server, srv MapreduceServer) {
	s.RegisterService(&_Mapreduce_serviceDesc, srv)
}

var _Mapreduce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Mapreduce",
	HandlerType: (*MapreduceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
}
